[colors]
background = #282828
foreground = #EBDBB2
green = #b8bb26
disabled = #928374

[bar/main]
width = 100%
height = 20pt
radius = 2
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 3pt
border-color = #00000000
padding-left = 0
padding-right = 1
module-margin = 1
separator = ""
separator-foreground = ${colors.disabled}
font-0 = "JetBrainsMono Nerd Font:size=10:weight=bold;2"

# Bar layout
modules-left = menu i3 xwindow
modules-center = date
modules-right = wifi pulseaudio battery
; modules-right = pulseaudio tray battery powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; [module/tray]
; type = internal/tray
; format-margin = 4pt
; tray-spacing = 10pt

[module/i3]
type = internal/i3

; Focused workspace
label-focused = %index%
label-focused-foreground = ${colors.green}
label-focused-padding = 1

; Unfocused workspace
label-unfocused = %index%
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 1

; Separator
label-separator = |
label-separator-foreground = ${colors.disabled}

[module/xwindow]
type = internal/xwindow
label = %title:0:24:...%

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "  "

format-volume-prefix-foreground = ${colors.green}
format-volume = <label-volume>
label-volume = %{F#ebdbb2}%percentage%%
label-muted = muted
label-muted-foreground = ${colors.disabled}

; TODO: script and color
; [module/powermenu]
; type = custom/script
; exec = echo "%{F#88c0d0}⏻%{F-}%{F#6272a4}  |%{F-}"          
; click-left = bash -c "/home/siddharth/.config/rofi/powermenu/type-5/powermenu.sh"
[module/menu]
type = custom/script
exec = echo " %{F-}%{F#83a598}%{F-}"
click-left = exec rofi -modi run -show drun
; click-left = bash -c "/home/siddharth/.config/rofi/launchers/type-6/launcher.sh"
; click-right = /home/siddharth/.config/rofi/applets/bin/quicklinks.sh

[module/date]
type = internal/date
interval = 1
date =  %a.%d.%b,%R
label = %date%
label-foreground = ${colors.foreground}

[module/wifi]
type = internal/network
interface = wlan0
format-connected = <label-connected>
format-disconnected = <label-disconnected>

label-connected = %{F#b8bb26}󰤨  %{F-}%essid%
label-disconnected = %{F#928374}󰤭  disconnected

[module/battery]
type = internal/battery

battery = BAT1
adapter = AC
full-at = 98

format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>

label-charging = %{F#b8bb26}%{F-} %percentage%%
label-discharging = %{F#b8bb26}󰁾%{F-} %percentage%%
label-full = %{F#b8bb26}󰁹%{F-} %percentage%%

; // Nightlight option.
; "format": "󰖔 ",
; "format": "󰃠 ",
